name: mwindeler
favicon: null
layout_spectrum: 0.0474612507969141
typography_spectrum: 0.7793853480834514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1112954372074455
  lightness: 0.6351692792959511
  saturation: 0.007847093278542161
  rhythmicContrast: 0.5843637783546001
purpose: []
